version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: grep_api
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: db
    volumes:
      - .:/grep_api
    ports:
      - "3000:3000"
    depends_on:
      - db